openapi: 3.0.1
info:
  title: Workleap Domain Event Propagation
  description: .NET library offering a way for your service to publish domain events to EventGrid as well as listen to events published by other services.
  x-cortex-git:
    github:
      alias: gsoft-inc
      repository: gsoft-inc/wl-domain-event-propagation
  x-cortex-tag: service-wl-domain-event-propagation
  x-cortex-type: library
  x-cortex-slack:
    channels:
      - name: internal-dev-platform
        notificationsEnabled: true
  x-cortex-owners:
    - name: team-internal-developer-platform-backend
      type: GROUP
      provider: CORTEX
  x-cortex-link:
    - name: Documentation
      type: documentation
      url: https://gsoftdev.atlassian.net/wiki/spaces/TEC/pages/3711893755
    - type: cortex
      url: https://github.com/gsoft-inc/wl-domain-event-propagation/blob/main/.cortex/catalog/service-wl-domain-event-propagation.yaml
      name: Edit current Cortex entity in GitHub

